package com.puttysoftware.riskyrescue.assets;

public enum ObjectImage {
    ARMOR, ARROW_EAST, ARROW_NORTH, ARROW_NORTHEAST, ARROW_NORTHWEST, ARROW_SOUTH, ARROW_SOUTHEAST, ARROW_SOUTHWEST,
    ARROW_WEST, BUTTON, CLOSED_DOOR, GROUND, HAZARD, HEALER, OFF_WALL, OPEN_DOOR, REGENERATOR, WALL, WEAPONS, DARKNESS,
    DOWN, EMPTY, NOTE, SEALING_WALL, UP
}
